server:
  port: 9527
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka,http://localhost:3001/eureka
  instance:
    #instance-id: ${spring.cloud.client.ip-address}:${server.port} #此实例注册到eureka服务端的唯一的实例ID
    instance-id: getway001 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
spring:
  application:
    name: getway #此实例注册到eureka服务端的name

  cloud:
    gateway:
      enabled: true
      routes:
        - id: user  #自定义名字，全局唯一，建议服务名
          #uri: http://localhost:6001  #匹配后提供服务的路由路径
          uri: lb://user  #匹配后提供服务的路由路径
          predicates:
            - Path=/*    #断言，路径匹配的进行路由

        - id: order
          #uri: http://localhost:5000
          uri: lb://order  #匹配后提供服务的路由路径
          predicates:
            - Path=/*
      discovery:
        locator:
          enabled: true #开启动态路由，通过服务名来路由
          lower-case-service-id: true  #开启大小写
